version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build: .
    env_file: .env
    environment:
      POSTGRES_HOST: db
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  migrations:
     build: .
     depends_on:
       db:
         condition: service_healthy
     env_file:
       - .env
     command: sleep 5 && python manage.py migrate


  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - diplom_pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"

volumes:
  diplom_pg_data: