version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: matvey
      POSTGRES_DB: todolist_db
      POSTGRES_PASSWORD: 2898
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env


