version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/.env


  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env
    command: sleep 5 && python manage.py migrate

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data